<?php

/**
 * SSLCommerz Payment Initialization Response
 *
 * This class handles the response from a payment initialization request.
 * It provides methods to access the session key and payment gateway URL.
 *
 * @author Raiyan Sarker
 */

declare(strict_types=1);

namespace RaiyanSarker\SSLCommerz\Responses;

use Saloon\Http\Response;

/**
 * Class PaymentInitializationResponse
 *
 * The Saloon response class for payment initialization.
 *
 * @package RaiyanSarker\SSLCommerz\Responses
 * @author Raiyan Sarker
 *
 * @phpstan-type InitializationDetail array{
 *     status: string,
 *     failedreason: string|null,
 *     sessionkey: string|null,
 *     GatewayPageURL: string|null,
 *     store_id: string|null,
 *     verify_sign: string|null,
 *     verify_key: string|null
 * }
 */
class PaymentInitializationResponse extends Response
{
    /**
     * Get the status of the initialization.
     *
     * @return string The status (e.g., 'SUCCESS', 'FAILED').
     * @throws \JsonException If the response body could not be decoded as JSON.
     */
    public function getStatus(): string
    {
        $status = $this->json('status');
        return is_scalar($status) ? (string) $status : '';
    }

    /**
     * Check if the payment initialization was successful.
     *
     * @return bool True if successful, false otherwise.
     * @throws \JsonException If the response body could not be decoded as JSON.
     */
    public function isSuccess(): bool
    {
        return $this->getStatus() === 'SUCCESS';
    }

    /**
     * Get the session key generated by SSLCommerz.
     *
     * This key is required for redirecting the customer to the gateway.
     *
     * @return string|null The session key if available.
     * @throws \JsonException If the response body could not be decoded as JSON.
     */
    public function getSessionKey(): ?string
    {
        $value = $this->json('sessionkey');
        return is_string($value) ? $value : null;
    }

    /**
     * Get the payment gateway URL.
     *
     * This is the URL where the customer should be redirected to complete the payment.
     *
     * @return string|null The gateway page URL if available.
     * @throws \JsonException If the response body could not be decoded as JSON.
     */
    public function getGatewayPageURL(): ?string
    {
        $value = $this->json('GatewayPageURL');
        return is_string($value) ? $value : null;
    }

    /**
     * Get the reason for a failed initialization.
     *
     * @return string|null The failure reason if available.
     * @throws \JsonException If the response body could not be decoded as JSON.
     */
    public function getFailedReason(): ?string
    {
        $value = $this->json('failedreason');
        return is_string($value) ? $value : null;
    }

    /**
     * Get the full response data as an associative array.
     *
     * @return InitializationDetail The complete response data.
     * @throws \JsonException If the response body could not be decoded as JSON.
     */
    public function getData(): array
    {
        /** @var InitializationDetail $data */
        $data = $this->json();
        return $data;
    }
}
