<?php

/**
 * SSLCommerz Payment Data
 *
 * This class represents the data required to initialize a payment with SSLCommerz.
 * It encapsulates all customer, product, and transaction details.
 *
 * @author Raiyan Sarker
 */

declare(strict_types=1);

namespace RaiyanSarker\SSLCommerz\Data;

/**
 * Class PaymentData
 *
 * A data transfer object for SSLCommerz payment initialization.
 *
 * @package RaiyanSarker\SSLCommerz\Data
 * @author Raiyan Sarker
 * @phpstan-immutable
 *
 * @phpstan-type PaymentDataArray array{
 *     store_id: string,
 *     store_passwd: string,
 *     total_amount: string,
 *     currency: string,
 *     tran_id: string,
 *     success_url: string,
 *     fail_url: string,
 *     cancel_url: string,
 *     ipn_url?: string,
 *     cus_name: string,
 *     cus_email: string,
 *     cus_add1: string,
 *     cus_city: string,
 *     cus_country: string,
 *     cus_phone: string,
 *     cus_postcode: string,
 *     product_name: string,
 *     product_category: string,
 *     product_profile: string,
 *     shipping_method: string,
 *     multi_card_name?: string,
 *     value_a?: string,
 *     value_b?: string,
 *     value_c?: string,
 *     value_d?: string
 * }
 */
class PaymentData
{
    /**
     * Constructor for PaymentData.
     *
     * @param float $totalAmount The total amount to be paid by the customer.
     * @param string $currency The currency code (e.g., 'BDT', 'USD').
     * @param string $transactionId A unique transaction ID generated by the merchant (tran_id).
     * @param string $successUrl The URL where the customer will be redirected after a successful payment.
     * @param string $failUrl The URL where the customer will be redirected after a failed payment.
     * @param string $cancelUrl The URL where the customer will be redirected after cancelling the payment.
     * @param string $customerName The name of the customer.
     * @param string $customerEmail The email address of the customer.
     * @param string $customerAddress1 The primary address of the customer.
     * @param string $customerCity The city of the customer.
     * @param string $customerCountry The country of the customer.
     * @param string $customerPhone The phone number of the customer.
     * @param string $customerPostcode The postcode of the customer.
     * @param string $productName The name of the product being purchased.
     * @param string $productCategory The category of the product (e.g., 'Electronic', 'Service').
     * @param string $productProfile The profile of the product (default is 'general').
     * @param string $shippingMethod Whether shipping is required ('YES' or 'NO').
     * @param string|null $ipnUrl Optional IPN (Instant Payment Notification) callback URL.
     * @param string|null $multiCardName Optional comma-separated list of allowed card names.
     * @param string|null $valueA Optional extra reference value (value_a).
     * @param string|null $valueB Optional extra reference value (value_b).
     * @param string|null $valueC Optional extra reference value (value_c).
     * @param string|null $valueD Optional extra reference value (value_d).
     */
    public function __construct(
        public readonly float $totalAmount,
        public readonly string $currency,
        public readonly string $transactionId,
        public readonly string $successUrl,
        public readonly string $failUrl,
        public readonly string $cancelUrl,
        public readonly string $customerName,
        public readonly string $customerEmail,
        public readonly string $customerAddress1,
        public readonly string $customerCity,
        public readonly string $customerCountry,
        public readonly string $customerPhone,
        public readonly string $customerPostcode,
        public readonly string $productName,
        public readonly string $productCategory,
        public readonly string $productProfile = 'general',
        public readonly string $shippingMethod = 'NO',
        public readonly ?string $ipnUrl = null,
        public readonly ?string $multiCardName = null,
        public readonly ?string $valueA = null,
        public readonly ?string $valueB = null,
        public readonly ?string $valueC = null,
        public readonly ?string $valueD = null,
    ) {
    }

    /**
     * Convert the payment data to an array for the SSLCommerz API.
     *
     * @param string $storeId The SSLCommerz store ID.
     * @param string $storePassword The SSLCommerz store password.
     * @return PaymentDataArray The formatted data for the API request.
     * @phpstan-pure
     */
    public function toArray(string $storeId, string $storePassword): array
    {
        $raw = [
            'store_id' => $storeId,
            'store_passwd' => $storePassword,
            'total_amount' => number_format($this->totalAmount, 2, '.', ''),
            'currency' => $this->currency,
            'tran_id' => $this->transactionId,
            'success_url' => $this->successUrl,
            'fail_url' => $this->failUrl,
            'cancel_url' => $this->cancelUrl,
            'ipn_url' => $this->ipnUrl,
            'cus_name' => $this->customerName,
            'cus_email' => $this->customerEmail,
            'cus_add1' => $this->customerAddress1,
            'cus_city' => $this->customerCity,
            'cus_country' => $this->customerCountry,
            'cus_phone' => $this->customerPhone,
            'cus_postcode' => $this->customerPostcode,
            'product_name' => $this->productName,
            'product_category' => $this->productCategory,
            'product_profile' => $this->productProfile,
            'shipping_method' => $this->shippingMethod,
            'multi_card_name' => $this->multiCardName,
            'value_a' => $this->valueA,
            'value_b' => $this->valueB,
            'value_c' => $this->valueC,
            'value_d' => $this->valueD,
        ];

        $data = [];
        foreach ($raw as $key => $value) {
            if ($value !== null) {
                $data[$key] = $value;
            }
        }

        /** @var PaymentDataArray $data */
        return $data;
    }
}
